run:
  skip-dirs-use-default: true
  skip-files:
    - _test.go
    - example/
linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: unhandled-error
        arguments: [ "fmt.*" ]
      - name: add-constant
        arguments:
          - maxLitCount: "2"
            allowStrs: '""'
            allowInts: "0,1,2"
            allowFloats: "0.0,0.,1.0,1.,2.0,2."
      - name: argument-limit
        arguments: [ 6 ]
      - name: atomic
      - name: bare-return
      - name: blank-imports
      - name: bool-literal-in-expr
      - name: call-to-gc
      - name: cognitive-complexity
        arguments: [ 10 ]
      - name: cyclomatic
        arguments: [ 6 ]
      - name: early-return
      - name: comment-spacings
      - name: confusing-naming # Methods or fields of struct
      - name: confusing-results
      - name: constant-logical-expr
      - name: context-as-argument
        arguments:
          - allowTypesBefore: "*testing.T,*github.com/user/repo/testing.Harness"
      - name: context-keys-type
      - name: datarace
      - name: deep-exit
      - name: defer
        arguments:
          - [ "call-chain", "loop" ]
      - name: empty-block
      - name: empty-lines
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: exported
        arguments: [ ]
      - name: function-result-limit
        arguments: [ 3 ]
      - name: function-length
        arguments: [ 0, 100 ]
      - name: get-return
      - name: identical-branches
      - name: if-return
      - name: increment-decrement
      - name: indent-error-flow
      - name: imports-blacklist
      - name: import-shadowing
      - name: line-length-limit
        arguments: [ 120 ]
      - name: modifies-parameter
      - name: modifies-value-receiver
      - name: nested-structs
      - name: optimize-operands-order
      - name: package-comments
      - name: range
      - name: range-val-in-closure
      - name: range-val-address
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: string-of-int
      - name: struct-tag
      - name: superfluous-else
      - name: time-equal
      - name: time-naming
      - name: var-naming
        arguments:
          - [ "ID" ] # AllowList
          - [ "VM" ] # DenyList
      - name: var-declaration
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unexported-return
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver
      - name: use-any # Since GO 1.18, interface{} has an alias: any. This rule proposes to replace instances of interface{} with any.
      - name: useless-break
      - name: waitgroup-by-value
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
  staticcheck:
    checks: [ "all" ] # https://staticcheck.io/docs/checks/
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - gofmt
    - goimports
    - revive